# -*- coding: utf-8 -*-
"""Customer_Segmentation_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQWmGCnU1l6A46Ul3IPm_mKxGUU_DlUs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/ifood_df.csv")

print(df.head())

print(df.info())

print(df.isnull().sum())

print(df.describe())

print(df.shape)

print(df.columns)

df['TotalPurchases'] = (
    df['NumWebPurchases'] +
    df['NumCatalogPurchases'] +
    df['NumStorePurchases']
)

print(df[['TotalPurchases']].head())

features = df[['Income', 'MntTotal', 'TotalPurchases', 'Recency']]

print(features.head())

plt.figure(figsize=(8,5))

sns.histplot(df['MntTotal'], bins=30)

plt.title("Customer Total Spending Distribution")

plt.xlabel("Total Spending")

plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

print(scaled_features[:5])

from sklearn.cluster import KMeans

inertia = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_features)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))

plt.plot(range(1,11), inertia, marker='o')

plt.title("Elbow Method")

plt.xlabel("Number of Clusters")

plt.ylabel("Inertia")

plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)

df['Cluster'] = kmeans.fit_predict(scaled_features)

print(df[['Income', 'MntTotal', 'TotalPurchases', 'Cluster']].head())

plt.figure(figsize=(10,6))

sns.scatterplot(
    x=df['Income'],
    y=df['MntTotal'],
    hue=df['Cluster'],
    palette='Set2'
)

plt.title("Customer Segments")

plt.xlabel("Income")

plt.ylabel("Total Spending")

plt.show()

cluster_summary = df.groupby('Cluster')[['Income', 'MntTotal', 'TotalPurchases']].mean()

print(cluster_summary)