# -*- coding: utf-8 -*-
"""Unveiling the Android App Market: Analyzing Google Play Store Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jLX_b9uUyZ9IDTHLiQbrCw6rcrJftE0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/apps-2.csv")

df.head()

df.shape

df.info()

df.isnull().sum()

df.drop('Unnamed: 0', axis=1, inplace=True)

df['Rating'] = df['Rating'].fillna(df['Rating'].median())

df.dropna(subset=['Current Ver'], inplace=True)

df.dropna(subset=['Android Ver'], inplace=True)

df['Installs'] = df['Installs'].str.replace(',', '')

df['Installs'] = df['Installs'].str.replace('+', '')

df['Installs'] = df['Installs'].astype(int)

df['Price'] = df['Price'].str.replace('$', '')

df['Price'] = df['Price'].astype(float)

df['Size'].unique()[:20]

plt.figure(figsize=(12,6))

df['Category'].value_counts().head(10).plot(kind='bar')

plt.title("Top 10 App Categories")

plt.xlabel("Category")

plt.ylabel("Number of Apps")

plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['Rating'], bins=20)

plt.title("Distribution of App Ratings")

plt.xlabel("Rating")

plt.ylabel("Count")

plt.show()

sns.countplot(x='Type', data=df)

plt.title("Free vs Paid Apps")

plt.show()

plt.figure(figsize=(8,5))

sns.scatterplot(x='Installs', y='Rating', data=df)

plt.title("Installs vs Ratings")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df['Price'])

plt.title("Price Distribution of Apps")

plt.show()