# -*- coding: utf-8 -*-
"""Fraud Detection Using Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qbKnYuQXOaviPEG-QCJP2fMfrnXisLE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/creditcard.csv")

df.head()

df.info()

df.isnull().sum()

df['Class'].value_counts()

df['Class'].value_counts(normalize=True) * 100

sns.countplot(x='Class', data=df)

plt.title("Fraud vs Non-Fraud Transactions")

plt.show()

X = df.drop('Class', axis=1)

y = df['Class']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

plt.figure(figsize=(6,4))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Fraud Detection Confusion Matrix")

plt.show()